/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Dell
 */
public class admin_admin extends javax.swing.JFrame {
    public Connection cn;
    public Statement st;
    public admin admin;
    /**
     * Creates new form admin_admin
     */
    public admin_admin() {
        initComponents();
        show_user();
    }
    public ArrayList<User_admin> userList()
    {     ArrayList<User_admin> userList = new ArrayList();
          try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm_new","root","");
            String queryl="select aid, user_name from admin";
            st=cn.createStatement();
            ResultSet rs=st.executeQuery(queryl);
            User_admin user;
            while(rs.next())
            {   user=new User_admin(rs.getString("aid"),rs.getString("user_name"));
                userList.add(user);
                
            
            }
          }
          catch(Exception e)
          {JOptionPane.showMessageDialog(null,e);
          }
          return userList;
    }
    public void show_user()
    {      ArrayList<User_admin> list = userList();
           DefaultTableModel model =(DefaultTableModel)display_admin.getModel();
           Object[] row = new Object[2];
           for(int i=0;i<list.size();i++)    
           {    row[0]=list.get(i).getadminid();
                row[1]=list.get(i).getadminname();
                model.addRow(row);
                
           
           
           }
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adid = new javax.swing.JTextField();
        adname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_admin = new javax.swing.JTable();
        insert = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel1.setText("admin id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel2.setText("admin name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        jPanel1.add(adid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 80, -1));
        jPanel1.add(adname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 80, -1));

        display_admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "aid", "user_name"
            }
        ));
        display_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_adminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(display_admin);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 290, -1));

        insert.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        insert.setText("insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        jPanel1.add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 110, -1));

        update.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        update.setText("update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 110, -1));

        delete.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 110, -1));

        back.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
         admin =new admin();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm_new","root","");
            PreparedStatement pt;
            pt = cn.prepareStatement("insert into admin(aid,user_name,is_super_admin)values(?,?,?)");
            pt.setString(1, adid.getText());
            pt.setString(2, adname.getText());
            pt.setString(3, "admin");
            pt.executeUpdate();
            DefaultTableModel model =(DefaultTableModel)display_admin.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null,"Insert sucessfully");
        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_insertActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
         try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm_new","root","");
            int row=display_admin.getSelectedRow();
            String value1=(display_admin.getModel().getValueAt(row, 0).toString());
            PreparedStatement pt;
            pt = cn.prepareStatement("UPDATE admin SET aid=?,user_name=? where aid=?");
            pt.setString(1, adid.getText());
            pt.setString(2, adname.getText());
            pt.setString(3, value1);
            pt.executeUpdate();
            DefaultTableModel model =(DefaultTableModel)display_admin.getModel();
            model.setRowCount(0);
            show_user();
            
            JOptionPane.showMessageDialog(null,"Update sucessfully");
            
        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm_new","root","");
            int row=display_admin.getSelectedRow();
            String value=(display_admin.getModel().getValueAt(row, 0).toString());
            PreparedStatement pt;
            //String sql="DELETE FROM lecturer where lec_name=?";
            pt = cn.prepareStatement("DELETE FROM admin where aid=?");
            pt.setString(1,value);
            pt.executeUpdate();
            DefaultTableModel model =(DefaultTableModel)display_admin.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null,"Delete sucessfully");
            
            
            
        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_deleteActionPerformed

    private void display_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_adminMouseClicked
       int i = display_admin.getSelectedRow();
        TableModel model = display_admin.getModel();
        adid.setText(model.getValueAt(i, 0).toString());
        adname.setText(model.getValueAt(i, 1).toString());
    }//GEN-LAST:event_display_adminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adid;
    private javax.swing.JTextField adname;
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JTable display_admin;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
