/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Dell
 */
public class admin_student extends javax.swing.JFrame {
    public Connection cn;
    public Statement st;
    String gender;
    public admin admin;
    public previous_education_results previous_education_results;
    public previous_education_results_1 previous_education_results_1;
    //String f;
    
    //private String firstname;
    
    /**
     * Creates new form admin_student
     */
    public admin_student() {
        initComponents();
        show_user();
      /*  String firstname=fname.getText();
        String lastname=lname.getText();
        String d1=date.getSelectedItem().toString();
        String d2=month.getSelectedItem().toString();
        String d3=year.getSelectedItem().toString();
        String dob=d1+d2+d3;
       // String gender;
        String faculty=fac.getSelectedItem().toString();
        String contactno =conno.getText();
        String email1=email.getText();
        String address=add.getText();
        String password1=String.valueOf(pass1.getPassword());*/
    }
    public ArrayList<User> userList()
    {     ArrayList<User> userList = new ArrayList();
          try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm_new","root","");
            String queryl="select *from student";
            st=cn.createStatement();
            ResultSet rs=st.executeQuery(queryl);
            User user;
            while(rs.next())
            {   user=new User(rs.getInt("id"),rs.getString("f_name"),rs.getString("l_name"),rs.getString("dob"),rs.getString("gender"),rs.getString("f_id"),rs.getInt("contact_no"),rs.getString("email"),rs.getString("address"),rs.getString("password"),rs.getString("intake"),rs.getString("course"),rs.getString("d_id"));
                userList.add(user);
                
            
            }
          }
          catch(Exception e)
          {JOptionPane.showMessageDialog(null,e);
          }
          return userList;
    }
    public void show_user()
    {      ArrayList<User> list = userList();
           DefaultTableModel model =(DefaultTableModel)display_user.getModel();
           Object[] row = new Object[13];
           for(int i=0;i<list.size();i++)    
           {    row[0]=list.get(i).getid();
                row[1]=list.get(i).getfname();
                row[2]=list.get(i).getlname();
                row[3]=list.get(i).getdate_of_birth();
                row[4]=list.get(i).getgender();
                row[5]=list.get(i).getfaculty();
                row[6]=list.get(i).getcontact();
                row[7]=list.get(i).getemail();
                row[8]=list.get(i).getaddress();
                row[9]=list.get(i).getpassword();
                row[10]=list.get(i).getintake();
                row[11]=list.get(i).getcourse();
                row[12]=list.get(i).getdegree();
                model.addRow(row);
                
           
           
           }
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        s_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        date = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        fac = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        conno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pass1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        intake_st = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        course_st = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        s_degree = new javax.swing.JComboBox<>();
        insert = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_user = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("faculty");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel14.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel14.setText("student id");

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel1.setText("First Name");

        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel2.setText("Last Name");

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel3.setText("Date Of Birth");

        date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996" }));
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel4.setText("Gender");

        buttonGroup1.add(male);
        male.setText("male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        buttonGroup1.add(female);
        female.setText("female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel9.setText("Faculty");

        fac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School of Business", "School of Computing", "School of Engineering" }));
        fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel6.setText("Contact no");

        conno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel7.setText("Email");

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel8.setText("Address");

        jLabel10.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel10.setText("Password");

        pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel11.setText("Intake");

        intake_st.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "february", "july" }));

        jLabel12.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel12.setText("Course");

        course_st.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bachelor", "Master " }));

        jLabel13.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel13.setText("Degree");

        s_degree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSc in Human Resource Management", "BSc in Logistics Management", "BSc in Project Management", "BSc in Industrial Management", "BA in Business Communication", "BM in Accounting & Finance ", "Bachelor of Interior Design", "BSc Management Information Systems", "BSc in Software Engineering", "BSc in Multimedia", "BSc in Computer Science", "BSc Engineering in Computer Systems Engineering", "Postgraduate Diploma in Human Resource Management", "Postgraduate Diploma in Business Management", "Master of Business Administration", "Postgraduate Diploma in Computer Networks" }));

        insert.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        insert.setText("insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        update.setText("update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        display_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "fname", "lname", "dob", "gender", "faculty", "contactno", "email", "address", "password", "intake", "course", "degree"
            }
        ));
        display_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(display_user);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel1))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s_degree, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course_st, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intake_st, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fac, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(male)
                        .addGap(18, 18, 18)
                        .addComponent(female))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addComponent(fname, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(s_id, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pass1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addComponent(add, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(conno, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(update)
                        .addGap(42, 42, 42)
                        .addComponent(delete)
                        .addGap(40, 40, 40)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(s_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(male)
                            .addComponent(female))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(fac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(conno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(intake_st, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(course_st, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(s_degree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(insert)
                        .addComponent(update)
                        .addComponent(delete)
                        .addComponent(back)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connoActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        String msg =s_id.getText();
       // f=fac.getSelectedItem().toString();
       // Connection cn=null;
        //PreparedStatement pt=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm_new","root","");
            PreparedStatement pt;
            pt = cn.prepareStatement("insert into student(id,f_name,l_name,dob,gender,f_id,contact_no,email,address,password,intake,course,d_id)values(?,?,?,?,?,(SELECT f_id FROM faculty WHERE name = ?),?,?,?,?,?,?,(SELECT d_id FROM degree WHERE d_name = ?))");
            pt.setString(1, s_id.getText());
            pt.setString(2, fname.getText());
            pt.setString(3, lname.getText());
            pt.setString(4, (date.getSelectedItem().toString()+month.getSelectedItem().toString()+year.getSelectedItem().toString()));
            if(male.isSelected())
            {gender="Male";}
            if(female.isSelected())
            {gender="Female";}
            pt.setString(5, gender);
            pt.setString(6, fac.getSelectedItem().toString());
            pt.setString(7, conno.getText());
            pt.setString(8, email.getText());
            pt.setString(9, add.getText());
            pt.setString(10, String.valueOf(pass1.getPassword()));
            pt.setString(11, intake_st.getSelectedItem().toString());
            pt.setString(12, course_st.getSelectedItem().toString());
            pt.setString(13, s_degree.getSelectedItem().toString());
            
            pt.executeUpdate();
            DefaultTableModel model =(DefaultTableModel)display_user.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null,"Insert sucessfully");
        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(null, e);
    }
        if(course_st.getSelectedItem().toString()=="Bachelor")
        {  previous_education_results =new previous_education_results(msg);
           previous_education_results.setVisible(true);
           this.dispose();
        }
        else
        {  previous_education_results_1 =new previous_education_results_1(msg);
           previous_education_results_1.setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_insertActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
         try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm_new","root","");
            int row=display_user.getSelectedRow();
            String value=(display_user.getModel().getValueAt(row, 0).toString());
          //  String query=
            PreparedStatement pt;
            pt = cn.prepareStatement("UPDATE student SET id=?,f_name=?,l_name=?,dob=?,gender=?,f_id=(SELECT f_id FROM faculty WHERE name = ?),contact_no=?,email=?,address=?,password=?,intake=?,course=?,d_id=(SELECT d_id FROM degree WHERE d_name = ?) where id="+value);
            //String firstname;
            pt.setString(1, s_id.getText());
            pt.setString(2, fname.getText());
            pt.setString(3, lname.getText());
            pt.setString(4, (date.getSelectedItem().toString()+month.getSelectedItem().toString()+year.getSelectedItem().toString()));
            if(male.isSelected())
            {gender="Male";}
            if(female.isSelected())
            {gender="Female";}
            pt.setString(5, gender);
            pt.setString(6, fac.getSelectedItem().toString());
            pt.setString(7, conno.getText());
            pt.setString(8, email.getText());
            pt.setString(9, add.getText());
            pt.setString(10, String.valueOf(pass1.getPassword()));
            pt.setString(11, intake_st.getSelectedItem().toString());
            pt.setString(12, course_st.getSelectedItem().toString());
            pt.setString(13, s_degree.getSelectedItem().toString());
            pt.executeUpdate();
            DefaultTableModel model =(DefaultTableModel)display_user.getModel();
            model.setRowCount(0);
            show_user();
            
            JOptionPane.showMessageDialog(null,"Update sucessfully");
            
            
         }
         catch(Exception e)
        {   JOptionPane.showMessageDialog(null, e);
    }
         
    }//GEN-LAST:event_updateActionPerformed

    private void display_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_userMouseClicked
        int i = display_user.getSelectedRow();
        TableModel model = display_user.getModel();
        s_id.setText(model.getValueAt(i, 0).toString());
        fname.setText(model.getValueAt(i, 1).toString());
        lname.setText(model.getValueAt(i, 2).toString());
      //  date.setText(model.getValueAt(i, 2).toString());
        String gender = model.getValueAt(i, 4).toString();
               if(gender.equals("Male"))
               {     male.setSelected(true);
               }
               else
               {     female.setSelected(true);
               }
        String faculty1= model.getValueAt(i, 5).toString();
            switch(faculty1){
                case "School of Business":
                    fac.setSelectedIndex(0);
                    break;
                case "School of Computing":
                    fac.setSelectedIndex(1);
                    break;
                case "School of Engineering":
                    fac.setSelectedIndex(2);
                    break;
            }
         conno.setText(model.getValueAt(i, 6).toString());
         email.setText(model.getValueAt(i, 7).toString());
         add.setText(model.getValueAt(i, 8).toString());
         pass1.setText(model.getValueAt(i, 9).toString());
         String intake= model.getValueAt(i, 10).toString();
            switch(intake){
                case "fabruary":
                    intake_st.setSelectedIndex(0);
                    break;
                case "july":
                    intake_st.setSelectedIndex(1);
                    break;
              }
          String course1= model.getValueAt(i, 11).toString();
            switch(course1){
                case "Bachelor":
                    course_st.setSelectedIndex(0);
                    break;
                case "Master":
                    intake_st.setSelectedIndex(1);
                    break;
              }  
        String degree1= model.getValueAt(i, 12).toString();
            switch(degree1){
                case "BSc in Human Resource Management":
                    s_degree.setSelectedIndex(0);
                    break;
                case "BSc in Logistics Management":
                    s_degree.setSelectedIndex(1);
                    break;
                case "BSc in Project Management":
                    s_degree.setSelectedIndex(2);
                    break;
                case "BSc in Industrial Management":
                    s_degree.setSelectedIndex(3);
                    break;
                case "BA in Business Communication":
                    s_degree.setSelectedIndex(4);
                    break;
                case "BM in Accounting & Finance":
                    s_degree.setSelectedIndex(5);
                    break;
                case "Bachelor of Interior Design":
                    s_degree.setSelectedIndex(6);
                    break;
                case "BSc Management Information Systems":
                    s_degree.setSelectedIndex(7);
                    break;
                case "BSc in Software Engineering":
                    s_degree.setSelectedIndex(8);
                    break;
                case "BSc in Multimedia":
                    s_degree.setSelectedIndex(9);
                    break;
                case "BSc in Computer Science":
                    s_degree.setSelectedIndex(10);
                    break;
                case "BSc Engineering in Computer Systems Engineering":
                    s_degree.setSelectedIndex(11);
                    break;
                case "Postgraduate Diploma in Human Resource Management":
                    s_degree.setSelectedIndex(12);
                    break;
                case "Postgraduate Diploma in Business Management":
                    s_degree.setSelectedIndex(13);
                    break;
                case "Master of Business Administration":
                    s_degree.setSelectedIndex(14);
                    break;
                case "Postgraduate Diploma in Computer Networks":
                    s_degree.setSelectedIndex(15);
                    break;
                    
                    
                    
                    
                    
                    
                    
                    
                    
              }  
        
    }//GEN-LAST:event_display_userMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm_new","root","");
            int row=display_user.getSelectedRow();
            String value=(display_user.getModel().getValueAt(row, 0).toString());
            PreparedStatement pt;
            pt = cn.prepareStatement("DELETE FROM student where id="+value);
            pt.executeUpdate();
            DefaultTableModel model =(DefaultTableModel)display_user.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null,"Delete sucessfully");
            
            
            
        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(null, e);
    }
        
        
        
        
    }//GEN-LAST:event_deleteActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        String f=fac.getSelectedItem().toString();
        admin=new admin(f);
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField conno;
    private javax.swing.JComboBox<String> course_st;
    private javax.swing.JComboBox<String> date;
    private javax.swing.JButton delete;
    private javax.swing.JTable display_user;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> fac;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.JButton insert;
    private javax.swing.JComboBox<String> intake_st;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JRadioButton male;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JComboBox<String> s_degree;
    private javax.swing.JTextField s_id;
    private javax.swing.JButton update;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
