/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Dell
 */
public class marks extends javax.swing.JFrame {
    public Connection cn;
    public Statement st;
    public admin admin;
    /**
     * Creates new form marks
     */
    public marks() {
        initComponents();
    }
    public ArrayList<User_marks> userList()
    {     ArrayList<User_marks> userList = new ArrayList();
          try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm_new","root","");
            String sql="select subject_1_id, subject_2_id ,subject_3_id ,subject_4_id from student_subjects where id = '"+id.getText()+"'";
            
            st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            User_marks user;
            while(rs.next())
            {   user=new User_marks(rs.getString("subject_1_id"),rs.getString("subject_2_id"),rs.getString("subject_3_id"),rs.getString("subject_4_id"));
                userList.add(user);
                
            
            }
          }
          catch(Exception e)
          {JOptionPane.showMessageDialog(null,e);
          }
          return userList;
    }
    public void show_user()
    {      ArrayList<User_marks> list = userList();
           DefaultTableModel model =(DefaultTableModel)display_sub.getModel();
           Object[] row = new Object[4];
           for(int i=0;i<list.size();i++)    
           {    row[0]=list.get(i).getsub1id();
                row[1]=list.get(i).getsub2id();
                row[2]=list.get(i).getsub3id();
                row[3]=list.get(i).getsub4id();
                model.addRow(row);
                
           
           
           }
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enter_id = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_sub = new javax.swing.JTable();
        sub1 = new javax.swing.JTextField();
        sub2 = new javax.swing.JTextField();
        sub3 = new javax.swing.JTextField();
        sub4 = new javax.swing.JTextField();
        mark1 = new javax.swing.JTextField();
        mark2 = new javax.swing.JTextField();
        mark3 = new javax.swing.JTextField();
        mark4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        gpa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enter_id.setBackground(new java.awt.Color(153, 153, 255));
        enter_id.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel1.setText("enter id");
        enter_id.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        enter_id.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 80, 20));

        jButton1.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        enter_id.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 130, -1));

        display_sub.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "subject_1_id", "subject_2_id", "subject_3_id", "subject_4_id"
            }
        ));
        display_sub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_subMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(display_sub);

        enter_id.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 360, -1));
        enter_id.add(sub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, -1));
        enter_id.add(sub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, -1));
        enter_id.add(sub3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, -1));
        enter_id.add(sub4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 110, -1));
        enter_id.add(mark1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 120, -1));
        enter_id.add(mark2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 120, -1));
        enter_id.add(mark3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 120, -1));
        enter_id.add(mark4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 120, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel2.setText("enter GPA");
        enter_id.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));
        enter_id.add(gpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 120, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel3.setText("marks");
        enter_id.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jButton2.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jButton2.setText("insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        enter_id.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 120, -1));

        jButton3.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        enter_id.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(enter_id, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(enter_id, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        show_user();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void display_subMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_subMouseClicked
        int i = display_sub.getSelectedRow();
        TableModel model = display_sub.getModel();
        sub1.setText(model.getValueAt(i, 0).toString());
        sub2.setText(model.getValueAt(i, 1).toString());
        sub3.setText(model.getValueAt(i, 2).toString());
        sub4.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_display_subMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm_new","root","");
            PreparedStatement pt;
            pt = cn.prepareStatement("insert into marks(id,subject_1_id,subject_2_id,subject_3_id,subject_4_id,subject_1_marks,subject_2_marks,subject_3_marks,subject_4_marks,GPA)values(?,?,?,?,?,?,?,?,?,?)");
            pt.setString(1, id.getText());
            pt.setString(2, sub1.getText());
            pt.setString(3, sub2.getText());
            pt.setString(4, sub3.getText());
            pt.setString(5, sub4.getText());
            pt.setString(6, mark1.getText());
            pt.setString(7, mark2.getText());
            pt.setString(8, mark3.getText());
            pt.setString(9, mark4.getText());
            pt.setString(10, gpa.getText());
            pt.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Insert sucessfully");
        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
              admin =new admin();
              admin.setVisible(true);
              this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new marks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable display_sub;
    private javax.swing.JPanel enter_id;
    private javax.swing.JTextField gpa;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mark1;
    private javax.swing.JTextField mark2;
    private javax.swing.JTextField mark3;
    private javax.swing.JTextField mark4;
    private javax.swing.JTextField sub1;
    private javax.swing.JTextField sub2;
    private javax.swing.JTextField sub3;
    private javax.swing.JTextField sub4;
    // End of variables declaration//GEN-END:variables
}
