/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class select_subject extends javax.swing.JFrame {
    public Connection cn;
    public Statement st;
    public String g;
    public int k;
    /**
     * Creates new form select_subject
     */
    public select_subject() {
        initComponents();
    }
    public select_subject(String para4) {
        initComponents();
        g=para4;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        semester = new javax.swing.JComboBox<>();
        enter = new javax.swing.JButton();
        s1 = new javax.swing.JComboBox<>();
        s2 = new javax.swing.JComboBox<>();
        s3 = new javax.swing.JComboBox<>();
        s4 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("year");

        jLabel2.setText("semester");

        jLabel3.setText("subject 1");

        jLabel4.setText("subject 2");

        jLabel5.setText("subject 3");

        jLabel6.setText("subject 4");

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", " ", " " }));

        semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        s1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Algorithm & data structures I", "Algorithm & data structures II", "Algorithm & data structures III", " " }));

        s2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "programming I", "programming II", "programming III" }));

        s3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "database I", "database II", "database III", "software engineering I", "software engineering II", "software engineering III", "laboratory" }));

        s4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "computer network I", "computer network II", "computer network III", "mathematics I", "mathematics II", "mathematics III", "statistics", "fundamental of computer science" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enter)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(year, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(semester, 0, 95, Short.MAX_VALUE))
                            .addComponent(s1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(s2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(s3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(s4, 0, 226, Short.MAX_VALUE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(enter)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        String year1=year.getSelectedItem().toString();
        String semester1=semester.getSelectedItem().toString();
        String subject1=s1.getSelectedItem().toString();
        String subject2=s2.getSelectedItem().toString();
        String subject3=s3.getSelectedItem().toString();
        String subject4=s4.getSelectedItem().toString();
        k=0;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm_new","root","");
            PreparedStatement pt;
           // PreparedStatement pt1;
          //  String q="SELECT SUM(no_of_credits) FROM subject WHERE sub_name = ? AND sub_name = ? AND sub_name = ?";
         //   String q1="insert into student_subjects(no_of_credits)value(SELECT SUM(no_of_credits) FROM subject WHERE sub_name = ? AND sub_name = ? AND sub_name = ? AND sub_name = ?)"; 
       //     String q="insert into student_subjects(id,year,semester,subject_1_id,subject_2_id,subject_3_id,subject_4_id,no_of_credits)values((SELECT id FROM student WHERE f_name = ?),?,?,(SELECT sub_id FROM subject WHERE sub_name = ?),(SELECT sub_id FROM subject WHERE sub_name = ?),(SELECT sub_id FROM subject WHERE sub_name = ?),(SELECT sub_id FROM subject WHERE sub_name = ?),(SELECT SUM(credits) FROM subject WHERE sub_name = ?))";
         //   pt1 =cn.prepareStatement("insert into student_subjects(no_of_credits)value(SELECT SUM(no_of_credits) FROM subject WHERE sub_name = ? AND sub_name = ? AND sub_name = ? AND sub_name = ?)");
            
           
          //  pt1 =cn.prepareStatement(q1);
           // pt1.setString(1, subject1);
           // pt1.setString(2, subject2);
           // pt1.setString(3, subject3);
           // pt1.setString(4, subject4);    
            
            pt =cn.prepareStatement("insert into student_subjects(id,year,semester,subject_1_id,subject_2_id,subject_3_id,subject_4_id,no_of_credits,full_payment)values((SELECT id FROM student WHERE password = ?),?,?,(SELECT sub_id FROM subject WHERE sub_name = ?),(SELECT sub_id FROM subject WHERE sub_name = ?),(SELECT sub_id FROM subject WHERE sub_name = ?),(SELECT sub_id FROM subject WHERE sub_name = ?),(SELECT SUM(credits) FROM subject WHERE sub_name = ? OR sub_name = ? OR sub_name = ? OR sub_name = ?),(SELECT SUM(fee) FROM subject WHERE sub_name = ? OR sub_name = ? OR sub_name = ? OR sub_name = ?))");
            pt.setString(1, g);
            pt.setString(2, year1);
            pt.setString(3, semester1);
            pt.setString(4, subject1);
            pt.setString(5, subject2);
            pt.setString(6, subject3);
            pt.setString(7, subject4);
          //  pt.setInt(8, k);
            pt.setString(8, subject1);
            pt.setString(9, subject2);
            pt.setString(10,subject3);
            pt.setString(11,subject4);
            pt.setString(12, subject1);
            pt.setString(13, subject2);
            pt.setString(14,subject3);
            pt.setString(15,subject4);
            
            //pt1.executeUpdate();
            pt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Insert sucessfully");
            
        }
         catch(Exception e)
        {   JOptionPane.showMessageDialog(null, e);
    }//GEN-LAST:event_enterActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(select_subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(select_subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(select_subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(select_subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new select_subject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> s1;
    private javax.swing.JComboBox<String> s2;
    private javax.swing.JComboBox<String> s3;
    private javax.swing.JComboBox<String> s4;
    private javax.swing.JComboBox<String> semester;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
