/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.text.SimpleDateFormat;

/**
 *
 * @author Dell
 */
public class subject extends javax.swing.JFrame {
    public Connection cn;
    public Statement st;
    public admin admin;
    String fac;
   // String []a =new String[5];
    /**
     * Creates new form subject
     */
    public subject() {
        initComponents();
      //  show_user();
      //  initaliseTheProductList();
        //getMktgAsstList();
    }
    public subject(String para1) {
        initComponents();
        fac=para1;
    }
   
   public ArrayList<User_subject> userList()
    {     ArrayList<User_subject> userList = new ArrayList();
          try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm_new","root","");
            PreparedStatement st;
            st = cn.prepareStatement("select sub_id, sub_name from subject where (year = ? and semester = ? and f_id =(SELECT f_id FROM student WHERE id = ?))");
          //  String sql1="selesct sub_id, sub_name from subject where year=? and semester=? ";
          //  PreparedStatement st = null;
            String id=enter.getText();
            int sid=Integer.parseInt(id);
            st.setString(1, year.getText());
            st.setString(2, semester.getText());
            st.setInt(3, sid);
            
            ResultSet rs=st.executeQuery();
            User_subject user;
            while(rs.next())
            {   user=new User_subject(rs.getString("sub_id"),rs.getString("sub_name"));
                userList.add(user);
                
            
            }
          }
          catch(Exception e)
          {JOptionPane.showMessageDialog(null,e);
          }
          return userList;
    }
   public void show_user()
    {      ArrayList<User_subject> list = userList();
           DefaultTableModel model =(DefaultTableModel)Display_subject.getModel();
           Object[] row = new Object[2];
           for(int i=0;i<list.size();i++)    
           {    
                row[0]=list.get(i).getsid();
                row[1]=list.get(i).getsubject();
                model.addRow(row);
                
           
           
           }
    
    
    
    }
   /* public void show_user()
    {      ArrayList<User_subject> list = userList();
           DefaultListModel model =(DefaultListModel)display_subject.getModel();
           Object[] row = new Object[1];
           for(int i=0;i<list.size();i++)    
           {    row[0]=list.get(i).getsubject();
                
               // model.addRow(row);
                model.addElement(row);
                display_subject.setModel(model);
           
           
           }
    
    
    
    }*/


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        enter = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Display_subject = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        semester = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sub1 = new javax.swing.JTextField();
        sub2 = new javax.swing.JTextField();
        sub3 = new javax.swing.JTextField();
        sub4 = new javax.swing.JTextField();
        enter_id = new javax.swing.JButton();
        enter_sub = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel1.setText("Enter id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        jPanel1.add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 110, 20));

        Display_subject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "sub_id", "sub_name"
            }
        ));
        jScrollPane1.setViewportView(Display_subject);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 310, 480));

        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel2.setText("year");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 110, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel3.setText("semester");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        jPanel1.add(semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 110, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel4.setText("subject1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel5.setText("subject2");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel6.setText("subject3");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel7.setText("subject4");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));
        jPanel1.add(sub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 110, -1));
        jPanel1.add(sub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 110, -1));
        jPanel1.add(sub3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 110, -1));
        jPanel1.add(sub4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 110, -1));

        enter_id.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        enter_id.setText("Enter");
        enter_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_idActionPerformed(evt);
            }
        });
        jPanel1.add(enter_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 110, -1));

        enter_sub.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        enter_sub.setText("Enter");
        enter_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_subActionPerformed(evt);
            }
        });
        jPanel1.add(enter_sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 110, -1));

        back.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enter_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_idActionPerformed
       show_user();// TODO add your handling code here:
    }//GEN-LAST:event_enter_idActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        admin =new admin();
        admin.setVisible(true);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void enter_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_subActionPerformed
        //String id=enter.getText();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd");
        Date date=new Date();
        String d =sdf.format(date);
        String[] result = d.split("/");
        int year2=Integer.parseInt(result[0]);
        int month2=Integer.parseInt(result[1]);
        int date2=Integer.parseInt(result[2]);
        int month3 =month2%10;
        
        
        
        String year1=year.getText();
        String semester1=semester.getText();
        String subject1=sub1.getText();
        String subject2=sub2.getText();
        String subject3=sub3.getText();
        String subject4=sub4.getText();
        //JOptionPane.showMessageDialog(null,year2+"\t"+year1+"\t"+semester1+"\t"+month3); 
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm_new","root","");
            PreparedStatement pt;  
            //if((year2==2018 && year1=="1" && semester1=="1" && month3<7 ))
            //{  
            pt =cn.prepareStatement("insert into student_subjects(id,year,semester,subject_1_id,subject_2_id,subject_3_id,subject_4_id,no_of_credits,full_payment)values(?,?,?,?,?,?,?,(SELECT SUM(credits) FROM subject WHERE sub_id = ? OR sub_id = ? OR sub_id = ? OR sub_id = ?),(SELECT SUM(fee) FROM subject WHERE sub_id = ? OR sub_id = ? OR sub_id = ? OR sub_id = ?))");
            pt.setString(1, enter.getText());
            
            pt.setString(2, year1);
            pt.setString(3, semester1);
            pt.setString(4, subject1);
            pt.setString(5, subject2);
            pt.setString(6, subject3);
            pt.setString(7, subject4);
          //  pt.setInt(8, k);
            pt.setString(8, subject1);
            pt.setString(9, subject2);
            pt.setString(10,subject3);
            pt.setString(11,subject4);
            pt.setString(12, subject1);
            pt.setString(13, subject2);
            pt.setString(14,subject3);
            pt.setString(15,subject4);
            
            //pt1.executeUpdate();
            pt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Insert sucessfully");
            //}
            //else
            //{JOptionPane.showMessageDialog(null,"cannot insert");}
        }
         catch(Exception e)
        {   JOptionPane.showMessageDialog(null, e);
    }                                     
    }//GEN-LAST:event_enter_subActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Display_subject;
    private javax.swing.JButton back;
    private javax.swing.JTextField enter;
    private javax.swing.JButton enter_id;
    private javax.swing.JButton enter_sub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField semester;
    private javax.swing.JTextField sub1;
    private javax.swing.JTextField sub2;
    private javax.swing.JTextField sub3;
    private javax.swing.JTextField sub4;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
